USE [master]
GO

/****** Object:  Database [EmployeeActivities]    Script Date: 6/11/2020 12:13:13 PM ******/
CREATE DATABASE [EmployeeActivities]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeActivities', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EmployeeActivities.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeActivities_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EmployeeActivities_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeActivities].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeActivities] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeeActivities] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeeActivities] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeeActivities] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeeActivities] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeeActivities] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeeActivities] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeActivities] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeActivities] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeActivities] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeeActivities] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeeActivities] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeActivities] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeeActivities] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeActivities] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeeActivities] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeActivities] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeActivities] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeActivities] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeActivities] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeActivities] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeeActivities] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeActivities] SET RECOVERY FULL 
GO

ALTER DATABASE [EmployeeActivities] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeActivities] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeActivities] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeActivities] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeActivities] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeeActivities] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeActivities] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmployeeActivities] SET  READ_WRITE 
GO


